<?php
declare(strict_types = 1);

namespace Tests\Innmind\AMQP\Model\Basic;

use Innmind\AMQP\Model\Basic\Consume;
use Innmind\Immutable\MapInterface;
use PHPUnit\Framework\TestCase;

class ConsumeTest extends TestCase
{
    public function testInterface()
    {
        $command = new Consume('queue');

        $this->assertSame('queue', $command->queue());
        $this->assertInstanceOf(MapInterface::class, $command->arguments());
        $this->assertSame('string', (string) $command->arguments()->keyType());
        $this->assertSame('mixed', (string) $command->arguments()->valueType());
        $this->assertCount(0, $command->arguments());
        $this->assertTrue($command->shouldAutoGenerateConsumerTag());
        $this->assertTrue($command->isLocal());
        $this->assertFalse($command->shouldAutoAcknowledge());
        $this->assertFalse($command->isExclusive());
        $this->assertTrue($command->shouldWait());
    }

    public function testWithConsumerTag()
    {
        $command = new Consume('queue');
        $command2 = $command->withConsumerTag('foo');

        $this->assertInstanceOf(Consume::class, $command2);
        $this->assertNotSame($command2, $command);
        $this->assertTrue($command->shouldAutoGenerateConsumerTag());
        $this->assertFalse($command2->shouldAutoGenerateConsumerTag());

        $command3 = $command2->withAutoGeneratedConsumerTag();

        $this->assertInstanceOf(Consume::class, $command3);
        $this->assertNotSame($command2, $command3);
        $this->assertFalse($command2->shouldAutoGenerateConsumerTag());
        $this->assertTrue($command3->shouldAutoGenerateConsumerTag());
    }

    public function testNoLocal()
    {
        $command = new Consume('queue');
        $command2 = $command->noLocal();

        $this->assertInstanceOf(Consume::class, $command2);
        $this->assertNotSame($command2, $command);
        $this->assertTrue($command->isLocal());
        $this->assertFalse($command2->isLocal());

        $command3 = $command2->local();

        $this->assertInstanceOf(Consume::class, $command3);
        $this->assertNotSame($command3, $command2);
        $this->assertFalse($command2->isLocal());
        $this->assertTrue($command3->isLocal());
    }

    public function testAutoAcknowledge()
    {
        $command = new Consume('queue');
        $command2 = $command->autoAcknowledge();

        $this->assertInstanceOf(Consume::class, $command2);
        $this->assertNotSame($command2, $command);
        $this->assertFalse($command->shouldAutoAcknowledge());
        $this->assertTrue($command2->shouldAutoAcknowledge());

        $command3 = $command2->manualAcknowledge();

        $this->assertInstanceOf(Consume::class, $command3);
        $this->assertNotSame($command2, $command3);
        $this->assertTrue($command2->shouldAutoAcknowledge());
        $this->assertFalse($command3->shouldAutoAcknowledge());
    }

    public function testExclusive()
    {
        $command = new Consume('queue');
        $command2 = $command->exclusive();

        $this->assertInstanceOf(Consume::class, $command2);
        $this->assertNotSame($command2, $command);
        $this->assertFalse($command->isExclusive());
        $this->assertTrue($command2->isExclusive());

        $command3 = $command2->notExclusive();

        $this->assertInstanceOf(Consume::class, $command3);
        $this->assertNotSame($command2, $command3);
        $this->assertTrue($command2->isExclusive());
        $this->assertFalse($command3->isExclusive());
    }

    public function testDontWait()
    {
        $command = new Consume('queue');
        $command2 = $command->dontWait();

        $this->assertInstanceOf(Consume::class, $command2);
        $this->assertNotSame($command2, $command);
        $this->assertTrue($command->shouldWait());
        $this->assertFalse($command2->shouldWait());

        $command3 = $command2->wait();

        $this->assertInstanceOf(Consume::class, $command3);
        $this->assertNotSame($command2, $command3);
        $this->assertFalse($command2->shouldWait());
        $this->assertTrue($command3->shouldWait());
    }
}
