<?php
declare(strict_types = 1);

namespace Innmind\AMQP\Model\Queue;

use Innmind\AMQP\Exception\{
    ExclusivePassiveDeclarationNotAllowed,
    NotWaitingPassiveDeclarationDoesNothing,
    PassiveQueueDeclarationMustHaveAName,
};
use Innmind\Immutable\{
    Map,
    Maybe,
};

/**
 * @psalm-immutable
 */
final class Declaration
{
    /** @var Maybe<string> */
    private Maybe $name;
    private bool $passive = false;
    private bool $durable = false;
    private bool $autoDelete = false;
    private bool $exclusive = false;
    private bool $wait = true;
    /** @var Map<string, mixed> */
    private Map $arguments;

    private function __construct()
    {
        /** @var Maybe<string> */
        $this->name = Maybe::nothing();
        /** @var Map<string, mixed> */
        $this->arguments = Map::of();
    }

    /**
     * Check if the queue exists on the server
     *
     * @psalm-pure
     */
    #[\NoDiscard]
    public static function passive(string $name): self
    {
        $self = new self;
        $self->passive = true;

        return $self->withName($name);
    }

    /**
     * The queue will survive after a server restart
     *
     * @psalm-pure
     */
    #[\NoDiscard]
    public static function durable(): self
    {
        $self = new self;
        $self->durable = true;

        return $self;
    }

    /**
     * The queue will disappear after a server restart
     *
     * @psalm-pure
     */
    #[\NoDiscard]
    public static function temporary(): self
    {
        return new self;
    }

    /**
     * The queue is deleted once all consumers have finished using it
     *
     * @psalm-pure
     */
    #[\NoDiscard]
    public static function autoDelete(): self
    {
        $self = new self;
        $self->autoDelete = true;

        return $self;
    }

    /**
     * Make the queue only accessible to the current connection
     */
    #[\NoDiscard]
    public function exclusive(): self
    {
        if ($this->isPassive()) {
            throw new ExclusivePassiveDeclarationNotAllowed;
        }

        $self = clone $this;
        $self->exclusive = true;

        return $self;
    }

    /**
     * Make the queue usable to all connections
     */
    #[\NoDiscard]
    public function notExclusive(): self
    {
        $self = clone $this;
        $self->exclusive = false;

        return $self;
    }

    /**
     * Don't wait for the server response
     */
    #[\NoDiscard]
    public function dontWait(): self
    {
        if ($this->isPassive()) {
            throw new NotWaitingPassiveDeclarationDoesNothing;
        }

        $self = clone $this;
        $self->wait = false;

        return $self;
    }

    /**
     * Wait for the server response
     */
    #[\NoDiscard]
    public function wait(): self
    {
        $self = clone $this;
        $self->wait = true;

        return $self;
    }

    /**
     * Name the queue with the given string
     */
    #[\NoDiscard]
    public function withName(string $name): self
    {
        $self = clone $this;
        $self->name = Maybe::just($name);

        return $self;
    }

    /**
     * Let the server generate a name for the queue
     */
    #[\NoDiscard]
    public function withAutoGeneratedName(): self
    {
        if ($this->isPassive()) {
            throw new PassiveQueueDeclarationMustHaveAName;
        }

        $self = clone $this;
        /** @var Maybe<string> */
        $self->name = Maybe::nothing();

        return $self;
    }

    #[\NoDiscard]
    public function withArgument(string $key, mixed $value): self
    {
        $self = clone $this;
        $self->arguments = ($self->arguments)($key, $value);

        return $self;
    }

    /**
     * @return Maybe<string>
     */
    #[\NoDiscard]
    public function name(): Maybe
    {
        return $this->name;
    }

    #[\NoDiscard]
    public function isPassive(): bool
    {
        return $this->passive;
    }

    #[\NoDiscard]
    public function isDurable(): bool
    {
        return $this->durable;
    }

    #[\NoDiscard]
    public function isAutoDeleted(): bool
    {
        return $this->autoDelete;
    }

    #[\NoDiscard]
    public function isExclusive(): bool
    {
        return $this->exclusive;
    }

    #[\NoDiscard]
    public function shouldWait(): bool
    {
        return $this->wait;
    }

    /**
     * @return Map<string, mixed>
     */
    #[\NoDiscard]
    public function arguments(): Map
    {
        return $this->arguments;
    }
}
