<?php
declare(strict_types = 1);

namespace Innmind\AMQP\Model\Basic;

use Innmind\AMQP\Exception\AutoGeneratedConsumerTagRequireServerResponse;
use Innmind\Immutable\{
    Map,
    Maybe,
};

/**
 * @psalm-immutable
 */
final class Consume
{
    private string $queue;
    /** @var Maybe<string> */
    private Maybe $consumerTag;
    private bool $local = true;
    private bool $ack = true;
    private bool $exclusive = false;
    private bool $wait = true;
    /** @var Map<string, mixed> */
    private Map $arguments;

    private function __construct(string $queue)
    {
        $this->queue = $queue;
        /** @var Maybe<string> */
        $this->consumerTag = Maybe::nothing();
        /** @var Map<string, mixed> */
        $this->arguments = Map::of();
    }

    /**
     * @psalm-pure
     */
    #[\NoDiscard]
    public static function of(string $queue): self
    {
        return new self($queue);
    }

    #[\NoDiscard]
    public function withConsumerTag(string $tag): self
    {
        $self = clone $this;
        $self->consumerTag = Maybe::just($tag);

        return $self;
    }

    /**
     * Let the server define the consumer tag
     */
    #[\NoDiscard]
    public function withAutoGeneratedConsumerTag(): self
    {
        $self = clone $this;
        /** @var Maybe<string> */
        $self->consumerTag = Maybe::nothing();

        return $self;
    }

    /**
     * Means the server will not deliver messages to the consumer
     */
    #[\NoDiscard]
    public function noLocal(): self
    {
        $self = clone $this;
        $self->local = false;

        return $self;
    }

    #[\NoDiscard]
    public function local(): self
    {
        $self = clone $this;
        $self->local = true;

        return $self;
    }

    #[\NoDiscard]
    public function manualAcknowledge(): self
    {
        $self = clone $this;
        $self->ack = true;

        return $self;
    }

    #[\NoDiscard]
    public function autoAcknowledge(): self
    {
        $self = clone $this;
        $self->ack = false;

        return $self;
    }

    #[\NoDiscard]
    public function exclusive(): self
    {
        $self = clone $this;
        $self->exclusive = true;

        return $self;
    }

    #[\NoDiscard]
    public function notExclusive(): self
    {
        $self = clone $this;
        $self->exclusive = false;

        return $self;
    }

    #[\NoDiscard]
    public function dontWait(): self
    {
        $_ = $this->consumerTag->match(
            static fn() => null,
            static fn() => throw new AutoGeneratedConsumerTagRequireServerResponse,
        );

        $self = clone $this;
        $self->wait = false;

        return $self;
    }

    #[\NoDiscard]
    public function wait(): self
    {
        $self = clone $this;
        $self->wait = true;

        return $self;
    }

    #[\NoDiscard]
    public function withArgument(string $key, mixed $value): self
    {
        $self = clone $this;
        $self->arguments = ($self->arguments)($key, $value);

        return $self;
    }

    #[\NoDiscard]
    public function queue(): string
    {
        return $this->queue;
    }

    /**
     * @return Maybe<string>
     */
    #[\NoDiscard]
    public function consumerTag(): Maybe
    {
        return $this->consumerTag;
    }

    #[\NoDiscard]
    public function isLocal(): bool
    {
        return $this->local;
    }

    #[\NoDiscard]
    public function shouldAutoAcknowledge(): bool
    {
        return !$this->ack;
    }

    #[\NoDiscard]
    public function isExclusive(): bool
    {
        return $this->exclusive;
    }

    #[\NoDiscard]
    public function shouldWait(): bool
    {
        return $this->wait;
    }

    /**
     * @return Map<string, mixed>
     */
    #[\NoDiscard]
    public function arguments(): Map
    {
        return $this->arguments;
    }
}
