name: CI

on: [push, pull_request]

jobs:
  blackbox:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        php-version: ['8.2', '8.3', '8.4']
        dependencies: ['lowest', 'highest']
    name: 'BlackBox (${{ matrix.os }}, ${{ matrix.php-version }}, ${{ matrix.dependencies }})'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: nijel/rabbitmq-action@v1.0.0
        with:
          rabbitmq version: '3.8-management'
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl
          coverage: xdebug
          ini-values: xdebug.max_nesting_level=2048
      - name: Composer
        uses: "ramsey/composer-install@v3"
        with:
          dependency-versions: ${{ matrix.dependencies }}
      - name: BlackBox
        run: php blackbox.php ci
  coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        php-version: ['8.2', '8.3', '8.4']
        dependencies: ['lowest', 'highest']
    name: 'Coverage (${{ matrix.os }}, ${{ matrix.php-version }}, ${{ matrix.dependencies }})'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: nijel/rabbitmq-action@v1.0.0
        with:
          rabbitmq version: '3.8-management'
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl
          coverage: xdebug
          ini-values: xdebug.max_nesting_level=2048
      - name: Composer
        uses: "ramsey/composer-install@v3"
        with:
          dependency-versions: ${{ matrix.dependencies }}
      - name: BlackBox
        run: php blackbox.php ci
        env:
          ENABLE_COVERAGE: 'true'
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  psalm:
    uses: innmind/github-workflows/.github/workflows/psalm-matrix.yml@main
  cs:
    uses: innmind/github-workflows/.github/workflows/cs.yml@main
    with:
      php-version: '8.2'
